image: "mikehibm/swagger-pdf-creator"
stages: 
  - deploy 
  - pdf

deploy:
  stage: deploy
  only: 
    - /^release-.*$/

  script:
    - ruby -v
    - dpl --provider=AzureWebApps --verbose    

pdf:
  stage: pdf
  only: 
    - /^release-.*$/

  script:
    - java -version
    - ruby -v

    # Build PDF file into /home/pdf/ directory.
    - cd /home && /home/build.sh $SWAGGER_JSON_URL output.pdf

    # Copy the created PDF file to the project directory. (Necessary to be able to be an artifact)
    - cp /home/pdf/output.pdf $CI_PROJECT_DIR/
    - ls -al /home/pdf/
    - ls -al $CI_PROJECT_DIR
  artifacts:
    paths:
      - output.pdf
    expire_in: 1 week
