image: "ubuntu:14.04"

build:
  before_script:
    - apt-get update && apt-get install -y software-properties-common curl git
    - add-apt-repository -y ppa:openjdk-r/ppa && add-apt-repository -y ppa:brightbox/ruby-ng && apt-get update && apt-get install -y openjdk-8-jdk ruby2.4
    - gem install --pre asciidoctor-pdf

  script:
    - java -version
    - ruby -v
    - cd ./MySampleWebApi.Doc && chmod +x *.sh && ./build.sh ./swagger.json
  artifacts:
    paths:
      - ./MySampleWebApi.Doc/pdf/out.pdf
